"""empty message

Revision ID: 1dc7aad679a8
Revises: fedeaee0299a
Create Date: 2023-10-22 14:43:51.989640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc7aad679a8'
down_revision = 'fedeaee0299a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("unique_email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("unique_email", type_='unique')
        batch_op.drop_column('email')


    # ### end Alembic commands ###
