"""empty message

Revision ID: 651ce4b2eb49
Revises: 85d66d4f0395
Create Date: 2023-10-13 00:22:19.590319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651ce4b2eb49'
down_revision = '85d66d4f0395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
